In [1]:
import numpy as np

Z wykorzystaniem biblioteki NumPy spróbuj zdefiniować:

1. wektor [1, 2, 3, 4]

In [2]:
wektor = np.array(range(1, 5))
wektor

array([1, 2, 3, 4])

2. macierz 2 x 4 złożoną z samych zer

In [3]:
macierz = np.zeros((2, 4))
macierz

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

3. macierz 2 X 5 złożoną z liczb losowych między 0 i 1

In [ ]:
macierz2 = np.random.random((2, 5))
macierz2

array([[0.41396674, 0.25177933, 0.38924108, 0.86090895, 0.02397914],
       [0.52776395, 0.83085888, 0.86903616, 0.11676432, 0.79118034]])

4. wyjaśnij, co robi funkcja dot?

In [5]:
macierz3 = np.array([1, 2,
                     3, 4])
macierz4 = np. array([4, 3,
                      2, 1])

np.dot(macierz3, macierz4)

20

`np.dot()` wykonuje działanie na dwóch macierzach, znane jako *dot product* - po polsku **iloczyn skalarny**  
$A \cdot B = A^TB$  
w skrocie to mnozy kazdy punkt w macierzy i dodaje do siebie uzyskujac jedna liczbe

___

Implementacja najprostszej sieci neuronowej z Python służącej do prognozowania, czy
pewna drużyna sportowa wygra rozgrywki (w dobie koronawirusa: e-Rozgrywki)
1. Wprowadź zmienną (o nazwie: weight) i przypisz jej wartość 0.1

In [6]:
weight = .1

2. Zdefiniuj prostą funkcję (o nazwie: neural_network) przyjmującą dwa parametry: input oraz utworzoną poprzednio wagę  
3. Funkcja powinna zwrócić zmienną (o nazwie: pred), w której przechowana będzie
wartość mnożenia (weight*input)

In [7]:
def neural_network(weight, input):
    pred = weight*input
    return pred

4. Prosta metoda powinna zostać przetestowana na następujących danych:  
- number_of_toes = [8.5, 9.5, 10, 9] - średnia liczba rzutów dla drużyny przed rozpoczęciem e-Rozgrywek
- input = number_of_toes[0]
- pred = neural_network(input,weight)


In [8]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(weight, input)

assert pred == 8.5*.1

5. Wyświetl uzyskany wynik i wpisz go w odpowiedziach  

In [9]:
pred

0.8500000000000001

6. Powtórz eksperyment dla pozostałych danych 9.5, 10 oraz 9

In [10]:
neural_network(number_of_toes[1], weight)

0.9500000000000001

In [11]:
neural_network(number_of_toes[2], weight)

1.0

Wykonamy teraz prognozę dla wielu danych wejściowych – w takim przypadku prosta sieć neuronowa powinna wykonywać bardziej dokładne prognozy  
zbiór toes – bieżąca średnia udanych rzutów na gracza  
zbiór wlrec – bieżąca liczba zwycięstw (procentowo)  
zbiór nfans – liczba kibiców (w milionach)  

In [42]:
toes =  [8.50, 9.50, 9.90, 9.00]
wlrec = [0.65, 0.80, 0.80, 0.90]
nfans = [1.20, 1.30, 0.50, 1.00]

input = [toes[0], wlrec[0], nfans[0]]
weights = [0.1, 0.2, 0.0]

In [ ]:
def w_sum(input, weights):
    return sum([i*w for i, w in zip(input, weights)]) if len(input)==len(weights) else None

In [44]:
def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

In [ ]:
pred([toes[0], wlrec[0], nfans[0]], [0.1, 0.2, 0.0])
#TODO: naprawic

TypeError: 'float' object is not callable